name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  path_file:
    description: 'file path'
    required: true
outputs:
  result:
    description: 'the result will be printed here'
runs:
  using: 'node12'
  main: 'dist/index.js'
